# Workflow to push a kernel to Kaggle
name: Kaggle kernel publisher

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bash $GITHUB_WORKSPACE/.github/tools/install.sh

      - name: Push Kaggle kernel
        run: bash $GITHUB_WORKSPACE/.github/tools/push.sh
        env:
            KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
            KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
